export const cocktails = [
    {
        name: "Cuba Libre",
        id: 0,
        image: "highball-lemon",
        glassware: "Highball",
        ice: "Cubed",
        method: "Build",
        garnish: "Lime Wedge",
        optional: "Cubata: Replace Light Rum with Dark Rum",
        short: "Rum, Lime, Cola",
        ingredients: {
            Rum: "50 ml",
            Lime: "12 ml",
            Sugar: "12 ml",
            Cola: "Fill",
        },
    },
    {
        name: "Tequila Sunrise",
        id: 1,
        image: "tropical",
        glassware: "Highball",
        ice: "Cubed",
        method: "Build & Sink",
        garnish: "",
        optional: "",
        short: "Tequila, Orange, Grenadine",
        ingredients: {
            Tequila: "50 ml",
            Orange: "Fill",
            Grenadine: "12 ml",
        },
    },
    {
        name: "Godfather",
        id: 1,
        image: "highball-mint",
        glassware: "Rocks",
        ice: "Cubed",
        method: "Build",
        garnish: "",
        optional: "Godmother: Replace Whisky with Vodka",
        short: "Whisky, Amaretto, Rocks",
        ingredients: {
            "Tequila second": "50 ml",
            Orange: "Fill",
            Grenadine: "12 ml",
        },
    },
    {
        name: "White Russian",
        id: 1,
        image: "highball-mint",
        glassware: "Rocks",
        ice: "Cubed",
        method: "Build",
        garnish: "",
        optional: "",
        short: "Vodka, Kahlua, Milk",
        ingredients: {
            Vodka: "37 ml",
            Kahlua: "25 ml",
            Milk: "Fill",
        },
    },
    {
        name: "Screaming Orgasm",
        id: 1,
        image: "highball-mint",
        glassware: "Rocks",
        ice: "Cubed",
        method: "Shake & Strain",
        garnish: "",
        optional: "Orgasm: No Vodka.",
        short: "Amaretto, Baileys, Milk",
        ingredients: {
            Vodka: "12 ml",
            Kahlua: "12 ml",
            Amaretto: "12 ml",
            Baileys: "12 ml",
            Milk: "50 ml",
        },
    },
    {
        name: "Moscow Mule",
        id: 1,
        image: "highball-long",
        glassware: "Highball / Copper Mug",
        ice: "Cubed",
        method: "Build",
        garnish: "Lime Wedge",
        optional:
            "Missouri: Replace Vodka with Southern Comfort\nJamaican: Replace Vodka with Spiced Rum",
        short: "Vodka, Ginger, Lime",
        ingredients: {
            Vodka: "50 ml",
            Lime: "25 ml",
            "Ginger Beer": "Fill",
        },
    },
    {
        name: "Woo Woo",
        id: 1,
        image: "highball-long",
        glassware: "Highball",
        ice: "Cubed",
        method: "Build",
        garnish: "Lime Wedge",
        optional: "Cape Codder: Replace Peach Liqueur with Vodka",
        short: "Vodka, Peach, Cranberry",
        ingredients: {
            Vodka: "25 ml",
            "Peach Liqueur": "25 ml",
            Cranberry: "Fill",
        },
    },
    {
        name: "Sea Breeze",
        id: 1,
        image: "highball-long",
        glassware: "Highball",
        ice: "Cubed",
        method: "Build & Float",
        garnish: "",
        optional:
            "Bay Freeze: Replace Grapefruit with Pineapple\nMadras: Replace Grapefruit with Orange",
        short: "Vodka, Cranberry, Grapefruit",
        ingredients: {
            Vodka: "50 ml",
            Cranberry: "75 ml",
            Grapefruit: "25 ml",
        },
    },
    {
        name: "El Diablo",
        id: 1,
        image: "highball-long",
        glassware: "Highball",
        ice: "Cubed",
        method: "Build",
        garnish: "Lime Wedge",
        optional: "",
        short: "Tequila, Cassis, Ginger",
        ingredients: {
            Tequila: "37 ml",
            "Cassis Liqueur": "12 ml",
            Lime: "12 ml",
            "Ginger Ale": "Fill",
        },
    },
    {
        name: "Sex on the Beach",
        id: 1,
        image: "tropical",
        glassware: "Highball",
        ice: "Cubed",
        method: "Build",
        garnish: "",
        optional: "",
        short: "Vodka, Peach, Cranberry, Orange",
        ingredients: {
            Vodka: "25 ml",
            "Peach Liqueur": "25 ml",
            Cranberry: "50 ml",
            Orange: "50 ml",
        },
    },
    {
        name: "Cosmopolitan",
        id: 1,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "Orange Zest",
        optional: "Flamed Orange Zest",
        short: "Vodka, Cointreau, Cranberry",
        ingredients: {
            "Citron Vodka": "37 ml",
            Cointreau: "12 ml",
            Lime: "12 ml",
            Cranberry: "25 ml",
        },
    },
    {
        name: "Daiquiri",
        id: 1,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "",
        optional: "Add fruit and fruit liqueur",
        short: "Light Rum, Lime",
        ingredients: {
            "Light Rum": "50 ml",
            Lime: "25 ml",
            Sugar: "12 ml",
        },
    },
    {
        name: "French Martini",
        id: 1,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "Raspberry",
        optional: "Muddle Fresh Pineapple, Pineapple Leaf",
        short: "Vodka, Chambord, Pineapple",
        ingredients: {
            Vodka: "37 ml",
            Chambord: "25 ml",
            Pineapple: "50 ml",
        },
    },
    {
        name: "Lynchburg Lemonade",
        id: 1,
        image: "highball-lemon",
        glassware: "Highball",
        ice: "Cubed",
        method: "Shake & Strain",
        garnish: "Lemon Wedge",
        optional: "",
        short: "Whisky, Cointreau, Lemonade",
        ingredients: {
            Whisky: "37 ml",
            Cointreau: "12 ml",
            Lemon: "25 ml",
            Sugar: "12 ml",
            Lemonade: "Fill",
        },
    },
    {
        name: "Bramble",
        id: 1,
        image: "margarita",
        glassware: "Highball",
        ice: "Crushed",
        method: "Build, Churn & Float",
        garnish: "Lemon Wedge & Blackberries",
        optional: "",
        short: "Gin, Brambleberry, Lemon",
        ingredients: {
            Gin: "37 ml",
            Lemon: "25 ml",
            Sugar: "12 ml",
            "Blackberry Liqueur": "12 ml",
        },
    },
    {
        name: "Mojito",
        id: 1,
        image: "highball-mint",
        glassware: "Highball",
        ice: "Crushed",
        method: "Muddle, Bash, Build & Churn",
        garnish: "Mint Sprig",
        optional: "Fruit Mojito: Add fruit and fruit liqueur",
        short: "Rum, Lime, Mint",
        ingredients: {
            "Lime Wedges": "4 wedges",
            Sugar: "12 ml",
            "Mint Leaves": "8-12 leaves",
            "Light Rum": "50 ml",
            Soda: "Fill",
        },
    },
    {
        name: "Caipirinha",
        id: 1,
        image: "highball-mint",
        glassware: "Rocks",
        ice: "Crushed",
        method: "Muddle, Build & Churn",
        garnish: "Lime Wedge",
        optional: "Caipiroska: Replace Cachaca with Vodka",
        short: "Cachaca, Lime, Sugar",
        ingredients: {
            "Lime wedges": "6 wedges",
            Sugar: "25 ml",
            Cachaca: "50 ml",
        },
    },
];
