export const cocktails = [
    {
        name: "Cuba Libre",
        id: 1,
        image: "highball-lemon",
        glassware: "Highball",
        ice: "Cubed",
        method: "Build",
        garnish: "Lime Wedge",
        optional: "Cubata: Replace Light Rum with Dark Rum",
        short: "Rum, Lime, Cola",
        ingredients: {
            Rum: "50 ml",
            Lime: "12 ml",
            Sugar: "12 ml",
            Cola: "Fill",
        },
    },
    {
        name: "Tequila Sunrise",
        id: 2,
        image: "tropical",
        glassware: "Highball",
        ice: "Cubed",
        method: "Build & Sink",
        garnish: "",
        optional: "",
        short: "Tequila, Orange, Grenadine",
        ingredients: {
            Tequila: "50 ml",
            Orange: "Fill",
            Grenadine: "12 ml",
        },
    },
    {
        name: "Godfather",
        id: 3,
        image: "highball-mint",
        glassware: "Rocks",
        ice: "Cubed",
        method: "Build",
        garnish: "",
        optional: "Godmother: Replace Whisky with Vodka",
        short: "Whisky, Amaretto, Rocks",
        ingredients: {
            "Tequila second": "50 ml",
            Orange: "Fill",
            Grenadine: "12 ml",
        },
    },
    {
        name: "White Russian",
        id: 4,
        image: "highball-mint",
        glassware: "Rocks",
        ice: "Cubed",
        method: "Build",
        garnish: "",
        optional: "",
        short: "Vodka, Kahlua, Milk",
        ingredients: {
            Vodka: "37 ml",
            Kahlua: "25 ml",
            Milk: "Fill",
        },
    },
    {
        name: "Screaming Orgasm",
        id: 5,
        image: "highball-mint",
        glassware: "Rocks",
        ice: "Cubed",
        method: "Shake & Strain",
        garnish: "",
        optional: "Orgasm: No Vodka.",
        short: "Amaretto, Baileys, Milk",
        ingredients: {
            Vodka: "12 ml",
            Kahlua: "12 ml",
            Amaretto: "12 ml",
            Baileys: "12 ml",
            Milk: "50 ml",
        },
    },
    {
        name: "Moscow Mule",
        id: 6,
        image: "highball-long",
        glassware: "Highball / Copper Mug",
        ice: "Cubed",
        method: "Build",
        garnish: "Lime Wedge",
        optional:
            "Missouri: Replace Vodka with Southern Comfort\nJamaican: Replace Vodka with Spiced Rum",
        short: "Vodka, Ginger, Lime",
        ingredients: {
            Vodka: "50 ml",
            Lime: "25 ml",
            "Ginger Beer": "Fill",
        },
    },
    {
        name: "Woo Woo",
        id: 7,
        image: "highball-long",
        glassware: "Highball",
        ice: "Cubed",
        method: "Build",
        garnish: "Lime Wedge",
        optional: "Cape Codder: Replace Peach Liqueur with Vodka",
        short: "Vodka, Peach, Cranberry",
        ingredients: {
            Vodka: "25 ml",
            "Peach Liqueur": "25 ml",
            Cranberry: "Fill",
        },
    },
    {
        name: "Sea Breeze",
        id: 8,
        image: "highball-long",
        glassware: "Highball",
        ice: "Cubed",
        method: "Build & Float",
        garnish: "",
        optional:
            "Bay Freeze: Replace Grapefruit with Pineapple\nMadras: Replace Grapefruit with Orange",
        short: "Vodka, Cranberry, Grapefruit",
        ingredients: {
            Vodka: "50 ml",
            Cranberry: "75 ml",
            Grapefruit: "25 ml",
        },
    },
    {
        name: "El Diablo",
        id: 9,
        image: "highball-long",
        glassware: "Highball",
        ice: "Cubed",
        method: "Build",
        garnish: "Lime Wedge",
        optional: "",
        short: "Tequila, Cassis, Ginger",
        ingredients: {
            Tequila: "37 ml",
            "Cassis Liqueur": "12 ml",
            Lime: "12 ml",
            "Ginger Ale": "Fill",
        },
    },
    {
        name: "Sex on the Beach",
        id: 10,
        image: "tropical",
        glassware: "Highball",
        ice: "Cubed",
        method: "Build",
        garnish: "",
        optional: "",
        short: "Vodka, Peach, Cranberry, Orange",
        ingredients: {
            Vodka: "25 ml",
            "Peach Liqueur": "25 ml",
            Cranberry: "50 ml",
            Orange: "50 ml",
        },
    },
    {
        name: "Cosmopolitan",
        id: 11,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "Orange Zest",
        optional: "Flamed Orange Zest",
        short: "Vodka, Cointreau, Cranberry",
        ingredients: {
            "Citron Vodka": "37 ml",
            Cointreau: "12 ml",
            Lime: "12 ml",
            Cranberry: "25 ml",
        },
    },
    {
        name: "Daiquiri",
        id: 12,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "",
        optional: "Add fruit and fruit liqueur",
        short: "Light Rum, Lime",
        ingredients: {
            "Light Rum": "50 ml",
            Lime: "25 ml",
            Sugar: "12 ml",
        },
    },
    {
        name: "French Martini",
        id: 13,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "Raspberry",
        optional: "Muddle Fresh Pineapple, Pineapple Leaf",
        short: "Vodka, Chambord, Pineapple",
        ingredients: {
            Vodka: "37 ml",
            Chambord: "25 ml",
            Pineapple: "50 ml",
        },
    },
    {
        name: "Lynchburg Lemonade",
        id: 14,
        image: "highball-lemon",
        glassware: "Highball",
        ice: "Cubed",
        method: "Shake & Strain",
        garnish: "Lemon Wedge",
        optional: "",
        short: "Whisky, Cointreau, Lemonade",
        ingredients: {
            Whisky: "37 ml",
            Cointreau: "12 ml",
            Lemon: "25 ml",
            Sugar: "12 ml",
            Lemonade: "Fill",
        },
    },
    {
        name: "Bramble",
        id: 15,
        image: "margarita",
        glassware: "Highball",
        ice: "Crushed",
        method: "Build, Churn & Float",
        garnish: "Lemon Wedge & Blackberries",
        optional: "",
        short: "Gin, Brambleberry, Lemon",
        ingredients: {
            Gin: "37 ml",
            Lemon: "25 ml",
            Sugar: "12 ml",
            "Blackberry Liqueur": "12 ml",
        },
    },
    {
        name: "Mojito",
        id: 16,
        image: "highball-mint",
        glassware: "Highball",
        ice: "Crushed",
        method: "Muddle, Bash, Build & Churn",
        garnish: "Mint Sprig",
        optional: "Fruit Mojito: Add fruit and fruit liqueur",
        short: "Rum, Lime, Mint",
        ingredients: {
            "Lime Wedges": "4 wedges",
            Sugar: "12 ml",
            "Mint Leaves": "8-12 leaves",
            "Light Rum": "50 ml",
            Soda: "Fill",
        },
    },
    {
        name: "Caipirinha",
        id: 17,
        image: "highball-mint",
        glassware: "Rocks",
        ice: "Crushed",
        method: "Muddle, Build & Churn",
        garnish: "Lime Wedge",
        optional: "Caipiroska: Replace Cachaca with Vodka",
        short: "Cachaca, Lime, Sugar",
        ingredients: {
            "Lime wedges": "6 wedges",
            Sugar: "25 ml",
            Cachaca: "50 ml",
        },
    },
    {
        name: "Horse's Neck",
        id: 18,
        image: "highball-lemon",
        glassware: "Highball",
        ice: "Cubed",
        method: "Build",
        garnish: "Lemon Spiral",
        optional: "Replace Bourbon with Brandy",
        short: "Bourbon, Ginger Ale, Bitters",
        ingredients: {
            "Angostura Bitters": "2 dashes",
            Bourbon: "50 ml",
            "Ginger Ale": "Fill",
        },
    },
    {
        name: "Tom Collins",
        id: 19,
        image: "highball-lemon",
        glassware: "Highball",
        ice: "Cubed",
        method: "Shake & Strain",
        garnish: "Lemon Wedge",
        optional: "John Collins: Replace Gin with Bourbon",
        short: "Gin, Lemon, Soda",
        ingredients: {
            Gin: "50 ml",
            Lemon: "25 ml",
            Sugar: "12 ml",
            Soda: "Top",
        },
    },
    {
        name: "Long Island Iced Tea",
        id: 20,
        image: "highball-long",
        glassware: "Highball",
        ice: "Cubed",
        method: "Shake & Strain",
        garnish: "Lemon Wedge",
        optional: "",
        short: "Diverse liquors, Cola",
        ingredients: {
            Vodka: "12 ml",
            Rum: "12 ml",
            Gin: "12 ml",
            Tequila: "12 ml",
            Cointreau: "12 ml",
            Lemon: "25 ml",
            Sugar: "12 ml",
            Cola: "Top",
        },
    },
    {
        name: "Dry Martini",
        id: 21,
        image: "martini",
        glassware: "Martini",
        ice: "Chilled glas",
        method: "Stir & Julep Strain",
        garnish: "Olives or Lemon Zest",
        optional:
            "Dirty: 2 Barspoons of Olive Brine.\nGibson: Garnish with Pearl Onions",
        short: "Vermouth, Olive, Vodka",
        ingredients: {
            "Dry Vermouth": "1 Barspoon",
            "Gin or Vodka": "60 ml",
        },
    },
    {
        name: "Manhatten",
        id: 22,
        image: "martini",
        glassware: "Martini",
        ice: "Chilled glas",
        method: "Stir & Julep Strain",
        garnish: "Cherry",
        optional: "Perfect: Also Dry Vermouth & both Garnishes",
        short: "Sweet Vermouth, Bitters, Bourbon",
        ingredients: {
            "Angostura Bitters": "2 dashes",
            Bourbon: "60 ml",
            "Sweet Vermouth": "25 ml",
        },
    },
    {
        name: "Batanga",
        id: 23,
        image: "highball-long",
        glassware: "Highball",
        ice: "Cubed",
        method: "Build",
        garnish: "Salt Rim",
        optional: "La Paloma: Replace Cola with Grapefruit soda",
        short: "Tequila, Lime, Cola",
        ingredients: {
            Tequila: "37 ml",
            Lime: "Juice from 1/2 lime",
            Cola: "Fill",
        },
    },
    {
        name: "Margarita",
        id: 24,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "Salt Rim (half)",
        optional: "Replace Cointreau and Sugar with agave syrup",
        short: "Tequila, Cointreau, Lime",
        ingredients: {
            Tequila: "37 ml",
            Cointreau: "12 ml",
            Lime: "25 ml",
            Sugar: "12 ml",
        },
    },
    {
        name: "Side Car",
        id: 25,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "Sugar Rim (Half, Full)",
        optional: "",
        short: "Cognac, Cointreau, Lemon",
        ingredients: {
            Cognac: "37 ml",
            Cointreau: "12 ml",
            Lemon: "25 ml",
            Sugar: "12 ml",
        },
    },
    {
        name: "Whiskey Sour",
        id: 26,
        image: "highball-lemon",
        glassware: "Rocks",
        ice: "Cubed",
        method: "Dry Shake, Shake & Strain",
        garnish: "Citrus & Cherry",
        optional:
            "New York Sour: Top with Red Wine\nAmaretto Sour: Replace Whiskey with Amaretto",
        short: "Whiskey, Egg White, Bitters",
        ingredients: {
            "Angostura Bitters": "2 dashes",
            "Egg White": "12 ml",
            Whiskey: "50 ml",
            Lemon: "25 ml",
            Sugar: "12 ml",
        },
    },
    {
        name: "Clover Club",
        id: 27,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Dry Shake, Shake & Fine Strain",
        garnish: "Raspberry, Powder Sugar",
        optional: "",
        short: "Raspberry, Egg White, Gin",
        ingredients: {
            "Egg White": "12 ml",
            "Raspberry syrup": "12 ml",
            Gin: "50 ml",
            Lemon: "25 ml",
            Sugar: "12 ml",
        },
    },
    {
        name: "B52",
        id: 28,
        image: "highball-mint",
        glassware: "Shooter",
        ice: "",
        method: "Layer in order",
        garnish: "",
        optional: "",
        short: "Kahlua, Baileys, Cointreau",
        ingredients: {
            Kahlua: "12 ml",
            Baileys: "12 ml",
            Cointreau: "12 ml",
        },
    },
    {
        name: "Pornstar Martini",
        id: 29,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "Passionfruit half",
        optional: "Champagne shot on the side",
        short: "Passionfruit, Vodka, Vanilla",
        ingredients: {
            Vodka: "50 ml",
            "Passionfruit Liqueur": "25 ml",
            "Passionfruit Puree": "25 ml",
            Lime: "12 ml",
            "Vanilla Syrup": "1 dash",
        },
    },
    {
        name: "Bellini",
        id: 30,
        image: "flute",
        glassware: "Flute",
        ice: "",
        method: "Build & Stir Gently",
        garnish: "",
        optional: "Rossini: Replace peach with raspberry puree & liqueur",
        short: "Peach, Prosecco",
        ingredients: {
            "Peach puree": "12 ml",
            "Peach liqueur": "12 ml",
            Prosecco: "Fill",
        },
    },
    {
        name: "French 75",
        id: 31,
        image: "flute",
        glassware: "Flute",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "Lemon Zest",
        optional: "",
        short: "Gin, Lemon, Prosecco",
        ingredients: {
            Gin: "25 ml",
            Lemon: "12 ml",
            Sugar: "6 ml",
            Prosecco: "Top",
        },
    },
    {
        name: "Old Fashioned",
        id: 32,
        image: "highball-lemon",
        glassware: "Rocks",
        ice: "Cubed",
        method: "Soak, Muddle, Build & Stir",
        garnish: "Orange Zest",
        optional: "",
        short: "Bitters, Sugar Cube, Bourbon",
        ingredients: {
            "Angostura soaked sugar cube": "1 cube",
            Soda: "1 barspoon",
            Bourbon: "50 ml",
        },
    },
    {
        name: "Dark & Stormy",
        id: 33,
        image: "highball-mint",
        glassware: "Highball",
        ice: "Cubed",
        method: "Build & Float",
        garnish: "Lime Wedge",
        optional: "Fidel Castro: Build and fill with Ginger Ale",
        short: "Black Rum, Ginger Beer, Lime",
        ingredients: {
            Lime: "25 ml",
            "Ginger Beer": "Fill",
            "Black Rum": "50 ml",
        },
    },
    {
        name: "Hemingway Daiquiri",
        id: 34,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "Cherry",
        optional: "On the Rocks",
        short: "Rum, Maraschino, Grapefruit",
        ingredients: {
            "Light Rum": "37 ml",
            Maraschino: "12 ml",
            Lime: "25 ml",
            Grapefruit: "25 ml",
        },
    },
    {
        name: "White Lady",
        id: 35,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "Lemon Zest",
        optional: "Pink Lady: 1 dash of Grenadine",
        short: "Gin, Cointreau, Lemon",
        ingredients: {
            Gin: "37 ml",
            Lemon: "25 ml",
            Cointreau: "12 ml",
            Sugar: "12 ml",
        },
    },
    {
        name: "Aviation",
        id: 36,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "Cherry",
        optional: "",
        short: "Gin, Maraschino, Cherry",
        ingredients: {
            Gin: "37 ml",
            Lemon: "25 ml",
            Maraschino: "12 ml",
            Sugar: "12 ml",
        },
    },
    {
        name: "Negroni",
        id: 37,
        image: "highball-lemon",
        glassware: "Rocks",
        ice: "Cubed",
        method: "Roll or Build & Stir",
        garnish: "Orange Zest or Slice",
        optional: "Boulevardier: Replace Gin with Bourbon",
        short: "Gin, Campari, Vermouth",
        ingredients: {
            Gin: "25 ml",
            Campari: "25 ml",
            "Sweet Vermouth": "25 ml",
        },
    },
    {
        name: "Aperol Spritz",
        id: 38,
        image: "highball-mint",
        glassware: "Wineglass",
        ice: "Cubed",
        method: "Build in Order",
        garnish: "Orance Slice",
        optional: "",
        short: "Prosecco, Aperol",
        ingredients: {
            Prosecco: "50 ml",
            Aperol: "25 ml",
            Soda: "12 ml",
        },
    },
    {
        name: "Espresso Martini",
        id: 39,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "3 Coffee Beans",
        optional: "",
        short: "Vodka, Kahlua, Espresso",
        ingredients: {
            Vodka: "37 ml",
            Kahlua: "25 ml",
            Espresso: "1 shot",
            Sugar: "5 ml",
        },
    },
    {
        name: "Brandy Alexander",
        id: 40,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "Grated Nutmeg",
        optional: "Replace Milk with Cream or Half & Half",
        short: "Brandy, Cacao Liqueur, Milk",
        ingredients: {
            Brandy: "37 ml",
            "Dark Cacao Liqueur": "25 ml",
            Milk: "50 ml",
        },
    },
    {
        name: "Grasshopper",
        id: 41,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "",
        optional: "Replace Milk with Cream or Half & Half",
        short: "Creme de Menthe, Cacao, Milk",
        ingredients: {
            "Green Creme de Menthe": "37 ml",
            "White Cacao Liqueur": "37 ml",
            Milk: "50 ml",
        },
    },
    {
        name: "Mai Tai",
        id: 42,
        image: "highball-mint",
        glassware: "Rocks or Tiki Mug",
        ice: "Crushed",
        method: "Shake, Strain & Float",
        garnish: "Mint Sprig",
        optional: "",
        short: "Rum, Cointreau, Lime, Orgreat",
        ingredients: {
            "Dark Rum": "37 ml",
            Cointreau: "12 ml",
            Lime: "12 ml",
            "Orgreat Syrup": "1 dash",
            "Overproof Rum (Float)": "12 ml",
        },
    },
    {
        name: "Blood & Sand",
        id: 43,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "Orange Zest",
        optional: "",
        short: "Whisky, Cherry, Vermouth, Orange",
        ingredients: {
            "Scotch Whisky": "25 ml",
            "Sweet Vermouth": "25 ml",
            "Cherry Brandy": "25 ml",
            Orange: "25 ml",
        },
    },
    {
        name: "Apple Martini",
        id: 44,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "Lemon Zest",
        optional: "Apple Leaf",
        short: "Vodka, Apple Liqueur, Lemon",
        ingredients: {
            Vodka: "37 ml",
            "Apple Liqueur": "12 ml",
            Lemon: "25 ml",
            Sugar: "12 ml",
        },
    },
    {
        name: "Singapore Sling",
        id: 45,
        image: "highball-long",
        glassware: "Highball / Sling",
        ice: "Cubed",
        method: "Shake & Strain",
        garnish: "Pineapple Wedge & Cherry",
        optional: "",
        short: "Pineapple, Gin, Brandy, Cointreau",
        ingredients: {
            "Angostura Bitters": "1 dash",
            Grenadine: "1 dash",
            Benedictine: "5 ml",
            Cointreau: "5 ml",
            "Cherry Brandy": "12 ml",
            Lime: "12 ml",
            Gin: "25 ml",
            Pineapple: "75 ml",
        },
    },
    {
        name: "Gimlet",
        id: 46,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Stir & Julep Strain",
        garnish: "Lime Zest",
        optional:
            "Pink Gin: Replace Lime Cordial with a few dashes of Angostura Bitters",
        short: "Gin, Lime Cordial",
        ingredients: {
            Gin: "60 ml",
            "Lime Cordial": "12 ml",
        },
    },
    {
        name: "Martinez",
        id: 47,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Stir & Julep Strain",
        garnish: "Lemon Zest",
        optional: "",
        short: "Orange Bitters, Maraschino, Vermouth",
        ingredients: {
            "Orange Bitters": "2 dashes",
            Maraschino: "1 barspoon",
            "Sweet Vermouth": "12 ml",
            Gin: "37 ml",
        },
    },
    {
        name: "Zombie",
        id: 48,
        image: "highball-long",
        glassware: "Highball / Tiki Mug",
        ice: "Crushed",
        method: "Shake & Strain",
        garnish: "Mint Sprig",
        optional: "Add falernum and garnish with cinnamon stick",
        short: "Bitters, Rum, Cinnamon, Absinthe",
        ingredients: {
            "Angostura Bitters": "4 dashes",
            Absinthe: "2 dashes",
            "Overproof Rum": "12 ml",
            "Dark Rum": "25 ml",
            "Light Rum": "12 ml",
            Grenadine: "12 ml",
            "Cinnamon Syrup": "25 ml",
            Lime: "25 ml",
            Grapefruit: "25 ml",
        },
    },
    {
        name: "Pina Colada",
        id: 49,
        image: "highball-long",
        glassware: "Highball / Hurricane",
        ice: "Cubed",
        method: "Shake & Strain",
        garnish: "Pineapple Wedge & Cherry",
        optional: "Blend fresh pineapple, cream, and coconut milk",
        short: "Rum, Coconut, Pineapple",
        ingredients: {
            "Light Rum": "37 ml",
            "Coconut Liqueur": "12 ml",
            "Coconut Syrup": "25 ml",
            Pineapple: "75 ml",
        },
    },
    {
        name: "Bloody Mary",
        id: 50,
        image: "highball-long",
        glassware: "Highball",
        ice: "Cubed / None",
        method: "Roll & Strain",
        garnish: "Celery Stick",
        optional:
            "Red Snapper: Replace Vodka with Gin, Black Pepper Rim, Lime Wedge",
        short: "Vodka, Tomato, Tabasco, Celery, Pepper",
        ingredients: {
            Vodka: "50 ml",
            Tomato: "75 ml",
            "Worcestershire Sauce": "3 dashes",
            Tabasco: "3 dashes",
            "Celery Salt": "1 pinch",
            Pepper: "1 pinch",
            Lime: "12 ml",
        },
    },
    {
        name: "Frozen Fruit Margarita",
        id: 51,
        image: "flute",
        glassware: "Wineglass / Hurricane",
        ice: "",
        method: "Blended",
        garnish: "Lime Wedge and Fruit Piece",
        optional: "",
        short: "Blended Fruit, Tequila, Lime, Ice",
        ingredients: {
            Fruit: "as desired",
            Tequila: "37 ml",
            "Fruit Liqueur": "12 ml",
            Lime: "25 ml",
            Sugar: "12 ml",
            "Crushed Ice": "1 scoop",
        },
    },
    {
        name: "Strawberry Daiquiri",
        id: 52,
        image: "martini",
        glassware: "Wineglass / Hurricane",
        ice: "",
        method: "Blended",
        garnish: "Strawberry & Sugar Rim",
        optional: "",
        short: "Light Rum, Strawberry, Lime",
        ingredients: {
            "Light Rum": "37 ml",
            "Strawberry Liqueur": "12 ml",
            Lime: "12 ml",
            "Strawberry Puree": "50 ml",
            "Crushed Ice": "1 scoop",
        },
    },
    {
        name: "Breakfast Martini",
        id: 53,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "Orange Zest",
        optional: "Slice of Toast",
        short: "Gin, Cointreau, Orange Marmelade",
        ingredients: {
            Gin: "37 ml",
            Cointreau: "12 ml",
            Lemon: "12 ml",
            "Orange Marmelade": "1 barspoon",
        },
    },
    {
        name: "Planters Punch",
        id: 54,
        image: "highball-mint",
        glassware: "Highball",
        ice: "Cubed",
        method: "Shake & Strain",
        garnish: "Mint Sprig",
        optional: "",
        short: "Rum, Orange, Pineapple, Grenadine",
        ingredients: {
            "Dark Rum": "50 ml",
            Orange: "37 ml",
            Pineapple: "37 ml",
            Lemon: "25 ml",
            Grenadine: "5 ml",
            Sugar: "5 ml",
            "Angostura Bitters": "2 dashes",
        },
    },
    {
        name: "Pisco Sour",
        id: 55,
        image: "highball-lemon",
        glassware: "Rocks",
        ice: "Cubed / None",
        method: "Dry Shake, Shake & Fine Strain",
        garnish: "",
        optional: "",
        short: "Pisco, Bitters, Egg White",
        ingredients: {
            "Angostura Bitters": "2 dashes",
            Pisco: "50 ml",
            Lemon: "25 ml",
            Sugar: "12 ml",
            "Egg White": "1 whole",
        },
    },
    {
        name: "Tokyo Iced Tea",
        id: 56,
        image: "highball-long",
        glassware: "Highball",
        ice: "",
        method: "Shake & Strain",
        garnish: "Lemon Wedge",
        optional: "",
        short: "Melon, Vodka, Rum, Gin, Tequila",
        ingredients: {
            Vodka: "12 ml",
            Rum: "12 ml",
            Gin: "12 ml",
            Tequila: "12 ml",
            "Melon Liqueur": "12 ml",
            Lemon: "25 ml",
            Sugar: "12 ml",
            Sprite: "Top",
        },
    },
    {
        name: "June Bug",
        id: 57,
        image: "highball-long",
        glassware: "Highball",
        ice: "Cubed",
        method: "Shake & Strain",
        garnish: "Pineapple Wedge",
        optional: "",
        short: "Melon, Malibu, Banana, Pineapple",
        ingredients: {
            "Melon Liqueur": "25 ml",
            Malibu: "12 ml",
            "Banana Liqueur": "12 ml",
            Lemon: "25 ml",
            Sugar: "12 ml",
            Pineapple: "50 ml",
        },
    },
    {
        name: "Treacle",
        id: 58,
        image: "glass",
        glassware: "Rocks",
        ice: "Cubed",
        method: "Soak, Muddle, Build & Stir",
        garnish: "2 Lemon Zest",
        optional: "",
        short: "Bitters, Rum, Cloudy Apple Juice",
        ingredients: {
            "Brown Sugar Cube": "1 cube",
            "Angostura Bitters": "soak",
            Soda: "1 barspoon",
            "Dark Rum": "50 ml",
            "Cloudy Apple Juice (Float)": "Fill",
        },
    },
    {
        name: "Pegu Club Cocktail",
        id: 59,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "Lime Zest",
        optional: "",
        short: "Gin, Cointreau, Lime, Bitters",
        ingredients: {
            Gin: "37 ml",
            Cointreau: "12 ml",
            Lime: "12 ml",
            "Angostura Bitters": "2 dashes",
        },
    },
    {
        name: "Between the Sheets",
        id: 60,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "Sugar Rim & Lemon Zest",
        optional: "Replace Light Rum with Benedictine",
        short: "Brandy, Rum, Cointreau, Lemon",
        ingredients: {
            "Brandy / Cognac": "25 ml",
            "Light Rum": "25 ml",
            Cointreau: "25 ml",
            Lemon: "12 ml",
        },
    },
    {
        name: "Brandy Crusta",
        id: 61,
        image: "martini",
        glassware: "Martini",
        ice: "",
        method: "Shake & Fine Strain",
        garnish: "Sugar Rim & Lemon Zest",
        optional: "",
        short: "Cognac, Cointreau, Maraschino",
        ingredients: {
            "Cognac / Brandy": "37 ml",
            Cointreau: "12 ml",
            Maraschino: "12 ml",
            Lemon: "25 ml",
        },
    },
    {
        name: "P2",
        id: 62,
        image: "highball-long",
        glassware: "Highball",
        ice: "Cubed",
        method: "Build",
        garnish: "Lime Wedge",
        optional: "P3: Use raspberry liqueur",
        short: "Vanilla Vodka, Apple Liqueur, Lime Cordial",
        ingredients: {
            "Vanilla Vodka": "20 ml",
            "Apple Liqueur": "20 ml",
            "Lime Cordial": "20 ml",
            Sprite: "Fill",
        },
    },
    {
        name: "Gin Basil Smash",
        id: 63,
        image: "highball-mint",
        glassware: "Highball",
        ice: "Cubed",
        method: "Shake & Fine Strain",
        garnish: "Basil Leaf",
        optional: "",
        short: "Gin, Basil, Lemon",
        ingredients: {
            Gin: "50 ml",
            Lemon: "25 ml",
            Sugar: "12 ml",
            Basil: "10 leaves",
        },
    },
];
